package com.enviro.assessment.grad001.kganyamaleka;


import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import java.time.LocalDateTime;

@Entity
@Data  // Lombok annotation to generate getters, setters, toString, equals, and hashCode
public class WasteCategory {

//    @CreationTimestamp
//    @Column(nullable = false, updatable = false)
//    private LocalDateTime created;
//
//    @UpdateTimestamp
//    @Column(nullable = false)
//    private LocalDateTime updated;


    @NotBlank(message = "name can not be blank")
    private String name;

    private String description;

    /**
     * The unique identifier for the waste category.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

}
