name: CI Pipeline

# Trigger the pipeline on push and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # The environment to run the job on (can be ubuntu, macos, windows)

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'

      # Build the project using Maven (adjust if using Gradle or another tool)
      - name: Build with Maven
        run: mvn clean install

      # Run tests
      - name: Run tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job will only run after the build job completes successfully

    steps:
      # Checkout the repository code again
      - name: Checkout code
        uses: actions/checkout@v2


